export const authConstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAILURE: "LOGOUT_FAILURE",

    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",
  };

  export const productConstants = {
    GET_ALL_PORTFOLIOS_REQUEST: "GET_ALL_PORTFOLIOS_REQUEST",
    GET_ALL_PORTFOLIOS_SUCCESS: "GET_ALL_PORTFOLIOS_SUCCESS",
    GET_ALL_PORTFOLIOS_FAILURE: "GET_ALL_PORTFOLIOS_FAILURE",
  
    DELETE_PORTFOLIO_BY_ID_REQUEST: "DELETE_PORTFOLIO_BY_ID_REQUEST",
    DELETE_PORTFOLIO_BY_ID_SUCCESS: "DELETE_PORTFOLIO_BY_ID_SUCCESS",
    DELETE_PORTFOLIO_BY_ID_FAILURE: "DELETE_PORTFOLIO_BY_ID_FAILURE",
  
    ADD_PORTFOLIO_REQUEST: "ADD_PORTFOLIO_REQUEST",
    ADD_PORTFOLIO_SUCCESS: "ADD_PORTFOLIO_SUCCESS",
    ADD_PORTFOLIO_FAILURE: "ADD_PORTFOLIO_FAILURE",
  };